name: Deploy to Server

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: List files in target directory
        run: ls -l target/

      - name: Deploy to Server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 134.209.148.84 >> ~/.ssh/known_hosts

          # Copy the JAR file to the server
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa target/restful-web-services-0.0.1-SNAPSHOT.jar root@134.209.148.84:/root/projects/Spring-Learning/

          # Execute the deploy script on the server
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@134.209.148.84 'cd /root/projects/Spring-Learning && ./deploy.sh'
