name: Deploy to Server

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Added this to avoid the 'distribution' error

      - name: Build with Maven
        run: mvn clean package

      - name: List files in target directory
        run: ls -l target/  # Added this to verify the JAR file is present

      - name: Deploy to Server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Copy the JAR file to the server
          scp -v -o StrictHostKeyChecking=no -i "$DEPLOY_KEY" target/restful-web-services-0.0.1-SNAPSHOT.jar root@134.209.148.84:/root/projects/Spring-Learning/

          # Execute the deploy script on the server
          ssh -v -o StrictHostKeyChecking=no -i "$DEPLOY_KEY" root@134.209.148.84 'cd /root/projects/Spring-Learning && ./deploy.sh'
