name: Deploy to Server

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Ensure that the correct JDK distribution is used

      - name: Build with Maven
        run: mvn clean package

      - name: List files in target directory
        run: ls -l target/  # Verify that the JAR file is present

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 134.209.148.84 >> ~/.ssh/known_hosts  # Add server to known hosts

      - name: Deploy to Server
        run: |
          # Copy the JAR file to the server
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa target/restful-web-services-0.0.1-SNAPSHOT.jar root@134.209.148.84:/root/projects/Spring-Learning/

          # Execute the deploy script on the server
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@134.209.148.84 'cd /root/projects/Spring-Learning && ./deploy.sh'
